---
- name: First play
  hosts: all
  tasks:
    - name: Ping all hosts
      ping:

- name: Sample playbook
  hosts: all
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: Hello World
